files:
  - .prettierrc:
      content: |
        {
          "semi": true,
          "trailingComma": "es5",
          "singleQuote": true,
          "endOfLine": "lf",
          "tabWidth": 2,
          "arrowParens": "always",
          "printWidth": 80,
          "bracketSpacing": true,
          "quoteProps": "as-needed",
          "proseWrap": "preserve"
        }
  - .prettierignore:
      content: |
        node_modules/
        dist/
